// Colorado ZIP code -> primary place (city/town) and county.
// Source: public US ZIP/county/city crosswalk (scpike/us-state-county-zip,
// Census-derived), filtered to real 5-digit Colorado ZIPs. Broomfield ZIPs
// (80020, 80023, 80038) are corrected to Broomfield County, which the source
// predates. A blank city means the source had no named place for that ZIP; the
// location filter falls back to the county in that case. County names carry the
// " County" suffix so they match the names used in the location list.
export type ColoradoZipArea = { city: string; county: string };
export const coloradoZipAreas: Record<string, ColoradoZipArea> = {
  "80002": { city: "Arvada", county: "Jefferson County" },
  "80003": { city: "Arvada", county: "Jefferson County" },
  "80004": { city: "Arvada", county: "Jefferson County" },
  "80005": { city: "Arvada", county: "Jefferson County" },
  "80007": { city: "", county: "Jefferson County" },
  "80010": { city: "Aurora", county: "Adams County" },
  "80011": { city: "Aurora", county: "Arapahoe County" },
  "80012": { city: "Aurora", county: "Arapahoe County" },
  "80013": { city: "Aurora", county: "Arapahoe County" },
  "80014": { city: "Aurora", county: "Arapahoe County" },
  "80015": { city: "Aurora", county: "Arapahoe County" },
  "80016": { city: "Aurora", county: "Arapahoe County" },
  "80017": { city: "Aurora", county: "Arapahoe County" },
  "80018": { city: "Aurora", county: "Arapahoe County" },
  "80019": { city: "Aurora", county: "Adams County" },
  "80020": { city: "Broomfield", county: "Broomfield County" },
  "80021": { city: "Westminster", county: "Jefferson County" },
  "80022": { city: "Commerce city", county: "Adams County" },
  "80024": { city: "Dupont", county: "Adams County" },
  "80025": { city: "Eldorado springs", county: "Boulder County" },
  "80026": { city: "Lafayette", county: "Boulder County" },
  "80027": { city: "Louisville", county: "Boulder County" },
  "80030": { city: "Westminster", county: "Adams County" },
  "80031": { city: "Westminster", county: "Adams County" },
  "80033": { city: "Wheat ridge", county: "Jefferson County" },
  "80101": { city: "Agate", county: "Elbert County" },
  "80102": { city: "Bennett", county: "Adams County" },
  "80103": { city: "Byers", county: "Arapahoe County" },
  "80104": { city: "Castle rock", county: "Douglas County" },
  "80105": { city: "Deer trail", county: "Arapahoe County" },
  "80106": { city: "Elbert", county: "El Paso County" },
  "80107": { city: "Elizabeth", county: "Elbert County" },
  "80110": { city: "Cherry hills vil", county: "Arapahoe County" },
  "80111": { city: "Cherry hills vil", county: "Arapahoe County" },
  "80112": { city: "Englewood", county: "Arapahoe County" },
  "80116": { city: "Franktown", county: "Douglas County" },
  "80117": { city: "Kiowa", county: "Elbert County" },
  "80118": { city: "Larkspur", county: "Douglas County" },
  "80120": { city: "Littleton", county: "Arapahoe County" },
  "80121": { city: "Greenwood villag", county: "Arapahoe County" },
  "80122": { city: "Littleton", county: "Arapahoe County" },
  "80123": { city: "Bow mar", county: "Jefferson County" },
  "80124": { city: "Littleton", county: "Douglas County" },
  "80125": { city: "Littleton", county: "Douglas County" },
  "80126": { city: "Highlands ranch", county: "Douglas County" },
  "80127": { city: "Littleton", county: "Jefferson County" },
  "80128": { city: "", county: "Jefferson County" },
  "80132": { city: "Monument", county: "El Paso County" },
  "80133": { city: "Palmer lake", county: "El Paso County" },
  "80134": { city: "Parker", county: "Douglas County" },
  "80135": { city: "Deckers", county: "Douglas County" },
  "80136": { city: "Strasburg", county: "Adams County" },
  "80137": { city: "Watkins", county: "Adams County" },
  "80138": { city: "", county: "Douglas County" },
  "80202": { city: "Denver", county: "Denver County" },
  "80203": { city: "Denver", county: "Denver County" },
  "80204": { city: "Denver", county: "Denver County" },
  "80205": { city: "Denver", county: "Denver County" },
  "80206": { city: "Denver", county: "Denver County" },
  "80207": { city: "Denver", county: "Denver County" },
  "80209": { city: "Denver", county: "Denver County" },
  "80210": { city: "Denver", county: "Denver County" },
  "80211": { city: "Denver", county: "Denver County" },
  "80212": { city: "Mountain view", county: "Denver County" },
  "80214": { city: "Edgewater", county: "Jefferson County" },
  "80215": { city: "Lakewood", county: "Jefferson County" },
  "80216": { city: "Denver", county: "Denver County" },
  "80218": { city: "Denver", county: "Denver County" },
  "80219": { city: "Denver", county: "Denver County" },
  "80220": { city: "Denver", county: "Denver County" },
  "80221": { city: "Federal heights", county: "Adams County" },
  "80222": { city: "Glendale", county: "Denver County" },
  "80223": { city: "Denver", county: "Denver County" },
  "80224": { city: "Denver", county: "Denver County" },
  "80226": { city: "Lakewood", county: "Jefferson County" },
  "80227": { city: "Denver", county: "Jefferson County" },
  "80228": { city: "Lakewood", county: "Jefferson County" },
  "80229": { city: "Thornton", county: "Adams County" },
  "80230": { city: "Lowry afb", county: "Denver County" },
  "80231": { city: "Denver", county: "Denver County" },
  "80232": { city: "Lakewood", county: "Jefferson County" },
  "80233": { city: "Northglenn", county: "Adams County" },
  "80234": { city: "Northglenn", county: "Adams County" },
  "80235": { city: "Denver", county: "Jefferson County" },
  "80236": { city: "Denver", county: "Denver County" },
  "80237": { city: "Denver", county: "Denver County" },
  "80239": { city: "Denver", county: "Denver County" },
  "80241": { city: "Northglenn", county: "Adams County" },
  "80246": { city: "", county: "Denver County" },
  "80249": { city: "Denver", county: "Denver County" },
  "80260": { city: "", county: "Adams County" },
  "80264": { city: "Lincoln center b", county: "Denver County" },
  "80290": { city: "Two united bank", county: "Denver County" },
  "80293": { city: "First interstate", county: "Denver County" },
  "80294": { city: "Denver", county: "Denver County" },
  "80301": { city: "Boulder", county: "Boulder County" },
  "80302": { city: "Boulder", county: "Boulder County" },
  "80303": { city: "Boulder", county: "Boulder County" },
  "80304": { city: "Boulder", county: "Boulder County" },
  "80401": { city: "Golden", county: "Jefferson County" },
  "80403": { city: "Golden", county: "Jefferson County" },
  "80420": { city: "Alma", county: "Park County" },
  "80421": { city: "Bailey", county: "Park County" },
  "80422": { city: "Black hawk", county: "Gilpin County" },
  "80423": { city: "Bond", county: "Eagle County" },
  "80424": { city: "Breckenridge", county: "Summit County" },
  "80425": { city: "Buffalo creek", county: "Jefferson County" },
  "80426": { city: "Burns", county: "Eagle County" },
  "80427": { city: "Central city", county: "Gilpin County" },
  "80428": { city: "Clark", county: "Routt County" },
  "80430": { city: "Coalmont", county: "Jackson County" },
  "80432": { city: "Como", county: "Park County" },
  "80433": { city: "Conifer", county: "Jefferson County" },
  "80434": { city: "Cowdrey", county: "Jackson County" },
  "80435": { city: "Keystone", county: "Summit County" },
  "80436": { city: "Dumont", county: "Clear Creek County" },
  "80438": { city: "Empire", county: "Clear Creek County" },
  "80439": { city: "Evergreen", county: "Jefferson County" },
  "80440": { city: "Fairplay", county: "Park County" },
  "80442": { city: "Fraser", county: "Grand County" },
  "80443": { city: "Copper mountain", county: "Summit County" },
  "80444": { city: "Georgetown", county: "Clear Creek County" },
  "80446": { city: "Granby", county: "Grand County" },
  "80447": { city: "Grand lake", county: "Grand County" },
  "80448": { city: "Grant", county: "Park County" },
  "80449": { city: "Hartsel", county: "Park County" },
  "80451": { city: "Hot sulphur spri", county: "Grand County" },
  "80452": { city: "Idaho springs", county: "Clear Creek County" },
  "80454": { city: "Indian hills", county: "Jefferson County" },
  "80455": { city: "Jamestown", county: "Boulder County" },
  "80456": { city: "Jefferson", county: "Park County" },
  "80457": { city: "Kittredge", county: "Jefferson County" },
  "80459": { city: "Kremmling", county: "Grand County" },
  "80461": { city: "Leadville", county: "Lake County" },
  "80463": { city: "Mc coy", county: "Eagle County" },
  "80465": { city: "Morrison", county: "Jefferson County" },
  "80466": { city: "Nederland", county: "Boulder County" },
  "80467": { city: "Oak creek", county: "Routt County" },
  "80468": { city: "Parshall", county: "Grand County" },
  "80469": { city: "Phippsburg", county: "Routt County" },
  "80470": { city: "Pine", county: "Jefferson County" },
  "80473": { city: "Rand", county: "Jackson County" },
  "80474": { city: "Rollinsville", county: "Gilpin County" },
  "80476": { city: "Silver plume", county: "Clear Creek County" },
  "80478": { city: "Tabernash", county: "Grand County" },
  "80479": { city: "Toponas", county: "Routt County" },
  "80480": { city: "Walden", county: "Jackson County" },
  "80481": { city: "Ward", county: "Boulder County" },
  "80482": { city: "Winter park", county: "Grand County" },
  "80483": { city: "Yampa", county: "Routt County" },
  "80487": { city: "Steamboat spring", county: "Routt County" },
  "80498": { city: "Silverthorne", county: "Summit County" },
  "80501": { city: "Longmont", county: "Boulder County" },
  "80503": { city: "Longmont", county: "Boulder County" },
  "80504": { city: "Longmont", county: "Weld County" },
  "80510": { city: "Allenspark", county: "Boulder County" },
  "80512": { city: "Bellvue", county: "Larimer County" },
  "80513": { city: "Berthoud", county: "Larimer County" },
  "80514": { city: "Dacono", county: "Weld County" },
  "80515": { city: "Drake", county: "Larimer County" },
  "80516": { city: "Erie", county: "Boulder County" },
  "80517": { city: "Estes park", county: "Larimer County" },
  "80520": { city: "Firestone", county: "Weld County" },
  "80521": { city: "Fort collins", county: "Larimer County" },
  "80524": { city: "Fort collins", county: "Larimer County" },
  "80525": { city: "Fort collins", county: "Larimer County" },
  "80526": { city: "Fort collins", county: "Larimer County" },
  "80528": { city: "", county: "Larimer County" },
  "80530": { city: "Frederick", county: "Weld County" },
  "80532": { city: "Glen haven", county: "Larimer County" },
  "80534": { city: "Johnstown", county: "Weld County" },
  "80535": { city: "Laporte", county: "Larimer County" },
  "80536": { city: "Virginia dale", county: "Larimer County" },
  "80537": { city: "Loveland", county: "Larimer County" },
  "80538": { city: "Loveland", county: "Larimer County" },
  "80540": { city: "Lyons", county: "Boulder County" },
  "80542": { city: "Mead", county: "Weld County" },
  "80543": { city: "Milliken", county: "Weld County" },
  "80545": { city: "Red feather lake", county: "Larimer County" },
  "80547": { city: "Timnath", county: "Larimer County" },
  "80549": { city: "Wellington", county: "Larimer County" },
  "80550": { city: "Windsor", county: "Weld County" },
  "80601": { city: "Lochbui", county: "Adams County" },
  "80610": { city: "Ault", county: "Weld County" },
  "80611": { city: "Briggsdale", county: "Weld County" },
  "80612": { city: "Carr", county: "Weld County" },
  "80615": { city: "Eaton", county: "Weld County" },
  "80620": { city: "Evans", county: "Weld County" },
  "80621": { city: "Wattenburg", county: "Weld County" },
  "80623": { city: "Gilcrest", county: "Weld County" },
  "80624": { city: "Gill", county: "Weld County" },
  "80631": { city: "Garden city", county: "Weld County" },
  "80634": { city: "Greeley", county: "Weld County" },
  "80640": { city: "Henderson", county: "Adams County" },
  "80642": { city: "Hudson", county: "Weld County" },
  "80643": { city: "Keenesburg", county: "Weld County" },
  "80644": { city: "Kersey", county: "Weld County" },
  "80645": { city: "La salle", county: "Weld County" },
  "80648": { city: "Nunn", county: "Weld County" },
  "80649": { city: "Orchard", county: "Morgan County" },
  "80650": { city: "Pierce", county: "Weld County" },
  "80651": { city: "Platteville", county: "Weld County" },
  "80652": { city: "Roggen", county: "Weld County" },
  "80653": { city: "Weldona", county: "Morgan County" },
  "80654": { city: "Hoyt", county: "Morgan County" },
  "80701": { city: "Fort morgan", county: "Morgan County" },
  "80705": { city: "Log lane village", county: "Morgan County" },
  "80720": { city: "Akron", county: "Washington County" },
  "80721": { city: "Amherst", county: "Phillips County" },
  "80722": { city: "Atwood", county: "Logan County" },
  "80723": { city: "Brush", county: "Morgan County" },
  "80726": { city: "Crook", county: "Logan County" },
  "80727": { city: "Eckley", county: "Yuma County" },
  "80728": { city: "Fleming", county: "Logan County" },
  "80729": { city: "Grover", county: "Weld County" },
  "80731": { city: "Haxtun", county: "Phillips County" },
  "80733": { city: "Hillrose", county: "Morgan County" },
  "80734": { city: "Holyoke", county: "Phillips County" },
  "80735": { city: "Hale", county: "Yuma County" },
  "80736": { city: "Iliff", county: "Logan County" },
  "80737": { city: "Julesburg", county: "Sedgwick County" },
  "80740": { city: "Lindon", county: "Washington County" },
  "80741": { city: "Willard", county: "Logan County" },
  "80742": { city: "New raymer", county: "Weld County" },
  "80743": { city: "Otis", county: "Washington County" },
  "80744": { city: "Ovid", county: "Sedgwick County" },
  "80745": { city: "Padroni", county: "Logan County" },
  "80747": { city: "Peetz", county: "Logan County" },
  "80749": { city: "Sedgwick", county: "Sedgwick County" },
  "80750": { city: "Snyder", county: "Morgan County" },
  "80751": { city: "Sterling", county: "Logan County" },
  "80754": { city: "Stoneham", county: "Weld County" },
  "80755": { city: "Vernon", county: "Yuma County" },
  "80757": { city: "Last chance", county: "Washington County" },
  "80758": { city: "Laird", county: "Yuma County" },
  "80759": { city: "Yuma", county: "Yuma County" },
  "80801": { city: "Anton", county: "Washington County" },
  "80802": { city: "Arapahoe", county: "Cheyenne County" },
  "80804": { city: "Arriba", county: "Lincoln County" },
  "80805": { city: "Bethune", county: "Kit Carson County" },
  "80807": { city: "Burlington", county: "Kit Carson County" },
  "80808": { city: "Calhan", county: "El Paso County" },
  "80809": { city: "North pole", county: "El Paso County" },
  "80810": { city: "Cheyenne wells", county: "Cheyenne County" },
  "80812": { city: "Cope", county: "Washington County" },
  "80813": { city: "Cripple creek", county: "Teller County" },
  "80814": { city: "Divide", county: "Teller County" },
  "80815": { city: "Flagler", county: "Kit Carson County" },
  "80816": { city: "Florissant", county: "Teller County" },
  "80817": { city: "Fountain", county: "El Paso County" },
  "80818": { city: "Genoa", county: "Lincoln County" },
  "80819": { city: "Green mountain f", county: "El Paso County" },
  "80820": { city: "Guffey", county: "Park County" },
  "80821": { city: "Hugo", county: "Lincoln County" },
  "80822": { city: "Joes", county: "Yuma County" },
  "80823": { city: "Karval", county: "Lincoln County" },
  "80824": { city: "Kirk", county: "Yuma County" },
  "80825": { city: "Kit carson", county: "Cheyenne County" },
  "80827": { city: "Lake george", county: "Park County" },
  "80828": { city: "Limon", county: "Lincoln County" },
  "80829": { city: "Manitou springs", county: "El Paso County" },
  "80830": { city: "Matheson", county: "Elbert County" },
  "80831": { city: "Peyton", county: "El Paso County" },
  "80832": { city: "Ramah", county: "El Paso County" },
  "80833": { city: "Rush", county: "El Paso County" },
  "80834": { city: "Seibert", county: "Kit Carson County" },
  "80835": { city: "Simla", county: "Elbert County" },
  "80836": { city: "Stratton", county: "Kit Carson County" },
  "80840": { city: "United states ai", county: "El Paso County" },
  "80860": { city: "Victor", county: "Teller County" },
  "80861": { city: "Vona", county: "Kit Carson County" },
  "80862": { city: "Wild horse", county: "Cheyenne County" },
  "80863": { city: "Woodland park", county: "Teller County" },
  "80864": { city: "Yoder", county: "El Paso County" },
  "80866": { city: "Woodland park", county: "Teller County" },
  "80903": { city: "Colorado springs", county: "El Paso County" },
  "80904": { city: "Colorado springs", county: "El Paso County" },
  "80905": { city: "Colorado springs", county: "El Paso County" },
  "80906": { city: "Colorado springs", county: "El Paso County" },
  "80907": { city: "Colorado springs", county: "El Paso County" },
  "80908": { city: "Colorado springs", county: "El Paso County" },
  "80909": { city: "Colorado springs", county: "El Paso County" },
  "80910": { city: "Colorado springs", county: "El Paso County" },
  "80911": { city: "Colorado springs", county: "El Paso County" },
  "80913": { city: "Fort carson", county: "El Paso County" },
  "80915": { city: "Colorado springs", county: "El Paso County" },
  "80916": { city: "Colorado springs", county: "El Paso County" },
  "80917": { city: "Colorado springs", county: "El Paso County" },
  "80918": { city: "Colorado springs", county: "El Paso County" },
  "80919": { city: "Colorado springs", county: "El Paso County" },
  "80920": { city: "Colorado springs", county: "El Paso County" },
  "80921": { city: "Colorado springs", county: "El Paso County" },
  "80922": { city: "Colorado springs", county: "El Paso County" },
  "80925": { city: "Colorado springs", county: "El Paso County" },
  "80926": { city: "Colorado springs", county: "El Paso County" },
  "80928": { city: "Colorado springs", county: "El Paso County" },
  "80929": { city: "Colorado springs", county: "El Paso County" },
  "80930": { city: "Colorado springs", county: "El Paso County" },
  "81001": { city: "Pueblo", county: "Pueblo County" },
  "81003": { city: "Pueblo", county: "Pueblo County" },
  "81004": { city: "Pueblo", county: "Pueblo County" },
  "81005": { city: "Pueblo", county: "Pueblo County" },
  "81006": { city: "Pueblo", county: "Pueblo County" },
  "81007": { city: "Pueblo west", county: "Pueblo County" },
  "81008": { city: "Pueblo", county: "Pueblo County" },
  "81020": { city: "Aguilar", county: "Las Animas County" },
  "81021": { city: "Arlington", county: "Kiowa County" },
  "81022": { city: "North avondale", county: "Pueblo County" },
  "81023": { city: "Beulah", county: "Pueblo County" },
  "81024": { city: "Boncarbo", county: "Las Animas County" },
  "81025": { city: "Boone", county: "Pueblo County" },
  "81027": { city: "Branson", county: "Las Animas County" },
  "81029": { city: "Campo", county: "Baca County" },
  "81030": { city: "Cheraw", county: "Otero County" },
  "81033": { city: "Crowley", county: "Crowley County" },
  "81036": { city: "Chivington", county: "Kiowa County" },
  "81039": { city: "Fowler", county: "Otero County" },
  "81040": { city: "Farisita", county: "Huerfano County" },
  "81041": { city: "Granada", county: "Prowers County" },
  "81043": { city: "Hartman", county: "Prowers County" },
  "81044": { city: "Caddoa", county: "Bent County" },
  "81045": { city: "Haswell", county: "Kiowa County" },
  "81047": { city: "Holly", county: "Prowers County" },
  "81049": { city: "Villegreen", county: "Las Animas County" },
  "81050": { city: "Timpas", county: "Otero County" },
  "81052": { city: "Lamar", county: "Prowers County" },
  "81054": { city: "Deora", county: "Bent County" },
  "81055": { city: "Cuchara", county: "Huerfano County" },
  "81057": { city: "Mc clave", county: "Bent County" },
  "81058": { city: "Manzanola", county: "Otero County" },
  "81059": { city: "Delhi", county: "Las Animas County" },
  "81062": { city: "Olney springs", county: "Crowley County" },
  "81063": { city: "Ordway", county: "Crowley County" },
  "81064": { city: "Utleyville", county: "Baca County" },
  "81066": { city: "Red wing", county: "Huerfano County" },
  "81067": { city: "Rocky ford", county: "Otero County" },
  "81069": { city: "Rye", county: "Pueblo County" },
  "81071": { city: "Towner", county: "Kiowa County" },
  "81073": { city: "Springfield", county: "Baca County" },
  "81076": { city: "Sugar city", county: "Crowley County" },
  "81077": { city: "Swink", county: "Otero County" },
  "81081": { city: "Trinchera", county: "Las Animas County" },
  "81082": { city: "Jansen", county: "Las Animas County" },
  "81084": { city: "Lycan", county: "Baca County" },
  "81087": { city: "Vilas", county: "Baca County" },
  "81089": { city: "Farista", county: "Huerfano County" },
  "81090": { city: "Walsh", county: "Baca County" },
  "81091": { city: "Weston", county: "Las Animas County" },
  "81092": { city: "Wiley", county: "Prowers County" },
  "81101": { city: "Alamosa", county: "Alamosa County" },
  "81120": { city: "Antonito", county: "Conejos County" },
  "81121": { city: "Arboles", county: "Archuleta County" },
  "81122": { city: "Bayfield", county: "La Plata County" },
  "81123": { city: "Blanca", county: "Costilla County" },
  "81124": { city: "Capulin", county: "Conejos County" },
  "81125": { city: "Center", county: "Saguache County" },
  "81126": { city: "Chama", county: "Costilla County" },
  "81127": { city: "Chimney rock", county: "Archuleta County" },
  "81128": { city: "Chromo", county: "Archuleta County" },
  "81130": { city: "Creede", county: "Mineral County" },
  "81131": { city: "Crestone", county: "Saguache County" },
  "81132": { city: "La garita", county: "Rio Grande County" },
  "81133": { city: "Fort garland", county: "Costilla County" },
  "81136": { city: "Hooper", county: "Alamosa County" },
  "81137": { city: "Ignacio", county: "La Plata County" },
  "81140": { city: "La jara", county: "Conejos County" },
  "81141": { city: "Manassa", county: "Conejos County" },
  "81143": { city: "Moffat", county: "Saguache County" },
  "81144": { city: "Monte vista", county: "Rio Grande County" },
  "81146": { city: "Mosca", county: "Alamosa County" },
  "81147": { city: "Pagosa springs", county: "Archuleta County" },
  "81148": { city: "Romeo", county: "Conejos County" },
  "81149": { city: "Saguache", county: "Saguache County" },
  "81151": { city: "Sanford", county: "Conejos County" },
  "81152": { city: "Mesita", county: "Costilla County" },
  "81153": { city: "San pablo", county: "Costilla County" },
  "81154": { city: "South fork", county: "Rio Grande County" },
  "81155": { city: "Villa grove", county: "Saguache County" },
  "81201": { city: "Salida", county: "Chaffee County" },
  "81210": { city: "Almont", county: "Gunnison County" },
  "81211": { city: "Buena vista", county: "Chaffee County" },
  "81212": { city: "Canon city", county: "Fremont County" },
  "81220": { city: "Cimarron", county: "Gunnison County" },
  "81221": { city: "Coal creek", county: "Fremont County" },
  "81222": { city: "Coaldale", county: "Fremont County" },
  "81223": { city: "Cotopaxi", county: "Fremont County" },
  "81224": { city: "Crested butte", county: "Gunnison County" },
  "81225": { city: "Crested butte", county: "Gunnison County" },
  "81226": { city: "Florence", county: "Fremont County" },
  "81230": { city: "Gunnison", county: "Gunnison County" },
  "81233": { city: "Howard", county: "Fremont County" },
  "81235": { city: "Lake city", county: "Hinsdale County" },
  "81236": { city: "Nathrop", county: "Chaffee County" },
  "81239": { city: "Parlin", county: "Gunnison County" },
  "81240": { city: "Penrose", county: "Fremont County" },
  "81241": { city: "Pitkin", county: "Gunnison County" },
  "81243": { city: "Powderhorn", county: "Gunnison County" },
  "81244": { city: "Rockvale", county: "Fremont County" },
  "81248": { city: "Sargents", county: "Saguache County" },
  "81251": { city: "Twin lakes", county: "Lake County" },
  "81252": { city: "Westcliffe", county: "Custer County" },
  "81253": { city: "Wetmore", county: "Custer County" },
  "81301": { city: "Durango", county: "La Plata County" },
  "81320": { city: "Cahone", county: "Dolores County" },
  "81321": { city: "Cortez", county: "Montezuma County" },
  "81323": { city: "Dolores", county: "Montezuma County" },
  "81324": { city: "Dove creek", county: "Dolores County" },
  "81325": { city: "Egnar", county: "San Miguel County" },
  "81326": { city: "Hesperus", county: "La Plata County" },
  "81327": { city: "Lewis", county: "Montezuma County" },
  "81328": { city: "Mancos", county: "Montezuma County" },
  "81330": { city: "Mesa verde natio", county: "Montezuma County" },
  "81331": { city: "Pleasant view", county: "Montezuma County" },
  "81332": { city: "Rico", county: "Dolores County" },
  "81334": { city: "Towaoc", county: "Montezuma County" },
  "81335": { city: "Yellow jacket", county: "Montezuma County" },
  "81401": { city: "Montrose", county: "Montrose County" },
  "81410": { city: "Austin", county: "Delta County" },
  "81411": { city: "Bedrock", county: "Montrose County" },
  "81413": { city: "Cedaredge", county: "Delta County" },
  "81415": { city: "Crawford", county: "Delta County" },
  "81416": { city: "Delta", county: "Delta County" },
  "81418": { city: "Eckert", county: "Delta County" },
  "81419": { city: "Hotchkiss", county: "Delta County" },
  "81422": { city: "Naturita", county: "Montrose County" },
  "81423": { city: "Norwood", county: "San Miguel County" },
  "81424": { city: "Nucla", county: "Montrose County" },
  "81425": { city: "Olathe", county: "Montrose County" },
  "81426": { city: "Ophir", county: "San Miguel County" },
  "81427": { city: "Ouray", county: "Ouray County" },
  "81428": { city: "Paonia", county: "Delta County" },
  "81430": { city: "Placerville", county: "San Miguel County" },
  "81431": { city: "Redvale", county: "Montrose County" },
  "81432": { city: "Ridgway", county: "Ouray County" },
  "81433": { city: "Silverton", county: "San Juan County" },
  "81434": { city: "Somerset", county: "Gunnison County" },
  "81435": { city: "Telluride", county: "San Miguel County" },
  "81501": { city: "Grand junction", county: "Mesa County" },
  "81503": { city: "Grand junction", county: "Mesa County" },
  "81504": { city: "Fruitvale", county: "Mesa County" },
  "81505": { city: "Grand junction", county: "Mesa County" },
  "81506": { city: "Grand junction", county: "Mesa County" },
  "81520": { city: "Clifton", county: "Mesa County" },
  "81521": { city: "Fruita", county: "Mesa County" },
  "81522": { city: "Gateway", county: "Mesa County" },
  "81523": { city: "Glade park", county: "Mesa County" },
  "81524": { city: "Loma", county: "Mesa County" },
  "81525": { city: "Mack", county: "Mesa County" },
  "81526": { city: "Palisade", county: "Mesa County" },
  "81527": { city: "Whitewater", county: "Mesa County" },
  "81601": { city: "Glenwood springs", county: "Garfield County" },
  "81610": { city: "Dinosaur", county: "Moffat County" },
  "81611": { city: "Aspen", county: "Pitkin County" },
  "81615": { city: "Snowmass village", county: "Pitkin County" },
  "81620": { city: "Avon", county: "Eagle County" },
  "81621": { city: "Basalt", county: "Eagle County" },
  "81623": { city: "Marble", county: "Garfield County" },
  "81624": { city: "Collbran", county: "Mesa County" },
  "81625": { city: "Craig", county: "Moffat County" },
  "81630": { city: "De beque", county: "Mesa County" },
  "81631": { city: "Eagle", county: "Eagle County" },
  "81632": { city: "Edwards", county: "Eagle County" },
  "81635": { city: "Battlement mesa", county: "Garfield County" },
  "81637": { city: "Gypsum", county: "Eagle County" },
  "81638": { city: "Hamilton", county: "Moffat County" },
  "81639": { city: "Hayden", county: "Routt County" },
  "81640": { city: "Maybell", county: "Moffat County" },
  "81641": { city: "Meeker", county: "Rio Blanco County" },
  "81642": { city: "Meredith", county: "Pitkin County" },
  "81643": { city: "Mesa", county: "Mesa County" },
  "81645": { city: "Gilman", county: "Eagle County" },
  "81646": { city: "Molina", county: "Mesa County" },
  "81647": { city: "New castle", county: "Garfield County" },
  "81648": { city: "Rangely", county: "Rio Blanco County" },
  "81649": { city: "Red cliff", county: "Eagle County" },
  "81650": { city: "Rifle", county: "Garfield County" },
  "81652": { city: "Silt", county: "Garfield County" },
  "81653": { city: "Slater", county: "Routt County" },
  "81654": { city: "Snowmass", county: "Pitkin County" },
  "81655": { city: "Wolcott", county: "Eagle County" },
  "81656": { city: "Woody creek", county: "Pitkin County" },
  "81657": { city: "Vail", county: "Eagle County" },
};
